main = ".open-next/worker.js"
name = "b3-web"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "bbyb.dev/*"
zone_id = "edbc6334a5f99b90be9a2c1c65876826"

[[routes]]
pattern = "www.bbyb.dev/*"
zone_id = "edbc6334a5f99b90be9a2c1c65876826"
